import type { TenantData } from './screening';

export interface ApplicantSample extends TenantData {
  id: string;
  neighborhood: 'Maple Heights' | 'Riverview' | 'Sunset Gardens';
  householdType: 'single' | 'couple' | 'family';
}

export const applicantSamples: ApplicantSample[] = [
  {
    id: 'A1',
    neighborhood: 'Maple Heights',
    householdType: 'couple',
    income: 72000,
    monthly_rent: 1800,
    debt: 15000,
    credit_score: 725,
    rental_history: { evictions: 0, late_payments: 1 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'strong', verified: true },
    payment_history: { on_time_rate: 0.96, records_available: true },
  },
  {
    id: 'A2',
    neighborhood: 'Maple Heights',
    householdType: 'family',
    income: 68000,
    monthly_rent: 2000,
    debt: 12000,
    credit_score: 705,
    rental_history: { evictions: 0, late_payments: 0 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'strong', verified: true },
    payment_history: { on_time_rate: 0.94, records_available: true },
  },
  {
    id: 'A3',
    neighborhood: 'Maple Heights',
    householdType: 'single',
    income: 54000,
    monthly_rent: 1700,
    debt: 9000,
    credit_score: 690,
    rental_history: { evictions: 0, late_payments: 0 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'part-time',
    landlord_reference: { rating: 'positive', verified: true },
    payment_history: { on_time_rate: 0.89, records_available: true },
  },
  {
    id: 'A4',
    neighborhood: 'Maple Heights',
    householdType: 'family',
    income: 59000,
    monthly_rent: 1600,
    debt: 22000,
    credit_score: 710,
    rental_history: { evictions: 0, late_payments: 3 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'neutral', verified: true },
    payment_history: { on_time_rate: 0.82, records_available: true },
  },
  {
    id: 'B1',
    neighborhood: 'Riverview',
    householdType: 'single',
    income: 48000,
    monthly_rent: 1600,
    debt: 8000,
    credit_score: 680,
    rental_history: { evictions: 0, late_payments: 1 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'positive', verified: true },
    payment_history: { on_time_rate: 0.9, records_available: true },
  },
  {
    id: 'B2',
    neighborhood: 'Riverview',
    householdType: 'family',
    income: 52000,
    monthly_rent: 1700,
    debt: 6000,
    credit_score: 670,
    rental_history: { evictions: 0, late_payments: 2 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'positive', verified: true },
    payment_history: { on_time_rate: 0.86, records_available: true },
  },
  {
    id: 'B3',
    neighborhood: 'Riverview',
    householdType: 'couple',
    income: 47000,
    monthly_rent: 1650,
    debt: 4000,
    credit_score: 660,
    rental_history: { evictions: 0, late_payments: 0 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'strong', verified: false },
    payment_history: { on_time_rate: 0.88, records_available: true },
  },
  {
    id: 'B4',
    neighborhood: 'Riverview',
    householdType: 'family',
    income: 50000,
    monthly_rent: 1850,
    debt: 9000,
    credit_score: 675,
    rental_history: { evictions: 0, late_payments: 1 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'positive', verified: true },
    payment_history: { on_time_rate: 0.87, records_available: true },
  },
  {
    id: 'C1',
    neighborhood: 'Sunset Gardens',
    householdType: 'single',
    income: 62000,
    monthly_rent: 2100,
    debt: 7000,
    credit_score: 735,
    rental_history: { evictions: 0, late_payments: 0 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'strong', verified: true },
    payment_history: { on_time_rate: 0.97, records_available: true },
  },
  {
    id: 'C2',
    neighborhood: 'Sunset Gardens',
    householdType: 'family',
    income: 75000,
    monthly_rent: 2300,
    debt: 18000,
    credit_score: 745,
    rental_history: { evictions: 0, late_payments: 1 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'strong', verified: true },
    payment_history: { on_time_rate: 0.93, records_available: true },
  },
  {
    id: 'C3',
    neighborhood: 'Sunset Gardens',
    householdType: 'couple',
    income: 80000,
    monthly_rent: 2400,
    debt: 25000,
    credit_score: 735,
    rental_history: { evictions: 0, late_payments: 0 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'positive', verified: true },
    payment_history: { on_time_rate: 0.9, records_available: true },
  },
  {
    id: 'C4',
    neighborhood: 'Sunset Gardens',
    householdType: 'family',
    income: 90000,
    monthly_rent: 2200,
    debt: 40000,
    credit_score: 760,
    rental_history: { evictions: 0, late_payments: 2 },
    criminal_background: { has_criminal_record: false },
    employment_status: 'full-time',
    landlord_reference: { rating: 'neutral', verified: true },
    payment_history: { on_time_rate: 0.85, records_available: true },
  },
];
